apiVersion: apps/v1
kind: Deployment
metadata:
  name: statichtml
  namespace: default
spec:
  selector:
    matchLabels:
      app: statichtml-app
  replicas: 1
  template:
    metadata:
      labels:
        app: statichtml-app
    spec:
      containers:
      - name: statichtml-app
        image: abvirk/statichtml:2
        ports:
        - containerPort: 8080