apiVersion: v1
kind: Service
metadata:
  name: statichtml
  namespace: default
spec:
  type: NodePort
  selector:
    app: statichtml
  ports:
  - port: 8080
    name: http
    protocol: TCP
    targetPort: 8080
    nodePort: 32762
