
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: statichtml
  name: statichtml
spec:
  type: NodePort
  ports:
    - name: "8080"
      port: 8080
      nodePort: 32762
      targetPort: 80
  selector:
    io.kompose.service: statichtml
status:
  loadBalancer: {}

